export const mockPartners = [
  "Grand Candy",
  "Ararat Agro",
  "Noyan Logistics",
  "Anahit Textile",
  "Van IT Solutions",
  "Yerevan Trade Hub",
  "Hayk Construction",
  "Sevan Foods",
  "Sasun Motors",
  "Arpi Energy",
  "Masis Pharma",
  "Dilijan Hospitality",
  "Ani Export Group",
  "Lori Fresh",
  "Tigran Finance",
  "Norik Digital",
  "Kilikia Beverages",
  "Arax Packaging",
  "Vardan Consulting",
  "Syunik Mining Service",
].map((name, index) => ({
  name: {
    am: name,
    ru: name,
    en: name,
  },
  description: {
    am: `${name}-ը հայկական ընկերություն է, որը ակտիվորեն համագործակցում է ABC ցանցում։`,
    ru: `${name} - армянская компания, активно развивающая сотрудничество в сети ABC.`,
    en: `${name} is an Armenian company actively building partnerships in the ABC network.`,
  },
  email: `contact${index + 1}@abcpartners.am`,
  location: "Yerevan, Armenia",
  phones: [`+374 91 1000${String(index).padStart(2, "0")}`],
  tags: [
    ["food", "export"],
    ["agriculture", "production"],
    ["logistics", "transport"],
    ["textile", "retail"],
    ["technology", "services"],
  ][index % 5],
}));
